//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NienLuanCoSo
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHIENDICH
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CHIENDICH()
        {
            this.TT_QUYENGOP_HIENVAT = new HashSet<TT_QUYENGOP_HIENVAT>();
            this.TT_TRAOTANG = new HashSet<TT_TRAOTANG>();
        }
    
        public int MA_CD { get; set; }
        public string TEN_CD { get; set; }
        public System.DateTime NGAYBATDAU { get; set; }
        public System.DateTime NGAYKETTHUC { get; set; }
        public string NOIDUNG_CD { get; set; }
        public string ANH_CD { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TT_QUYENGOP_HIENVAT> TT_QUYENGOP_HIENVAT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TT_TRAOTANG> TT_TRAOTANG { get; set; }
    }
}
