//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NienLuanCoSo
{
    using System;
    using System.Collections.Generic;
    
    public partial class HIEN_VAT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HIEN_VAT()
        {
            this.TT_QUYENGOP_HIENVAT = new HashSet<TT_QUYENGOP_HIENVAT>();
            this.TT_TRAOTANG = new HashSet<TT_TRAOTANG>();
        }
    
        public int MA_LOAI { get; set; }
        public int MA_HV { get; set; }
        public string TEN_HV { get; set; }
        public string DONVITINH { get; set; }
        public Nullable<int> SOLUONGCON { get; set; }
        public Nullable<int> GIA { get; set; }
    
        public virtual LOAI_HV LOAI_HV { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TT_QUYENGOP_HIENVAT> TT_QUYENGOP_HIENVAT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TT_TRAOTANG> TT_TRAOTANG { get; set; }
    }
}
