//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NienLuanCoSo
{
    using System;
    using System.Collections.Generic;
    
    public partial class MANHTHUONGQUAN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MANHTHUONGQUAN()
        {
            this.NOIHOTROes = new HashSet<NOIHOTRO>();
            this.TT_QUYENGOP_HIENVAT = new HashSet<TT_QUYENGOP_HIENVAT>();
        }
    
        public int MA_MTQ { get; set; }
        public string HOTEN_MTQ { get; set; }
        public System.DateTime NGAYSINH_MTQ { get; set; }
        public string GIOITINH_MTQ { get; set; }
        public string DONVI_TOCHUC_MTQ { get; set; }
        public int SDT_MTQ { get; set; }
        public string DIACHI_MTQ { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NOIHOTRO> NOIHOTROes { get; set; }
        public virtual TAIKHOAN_MTQ TAIKHOAN_MTQ { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TT_QUYENGOP_HIENVAT> TT_QUYENGOP_HIENVAT { get; set; }
    }
}
