//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NienLuanCoSo
{
    using System;
    using System.Collections.Generic;
    
    public partial class NOIHOTRO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NOIHOTRO()
        {
            this.TT_TRAOTANG = new HashSet<TT_TRAOTANG>();
        }
    
        public int MANOI { get; set; }
        public int MA__MTQ { get; set; }
        public string DIACHI { get; set; }
        public string TINHTRANG { get; set; }
        public string CANHOTRO { get; set; }
        public string TRANGTHAI_NHT { get; set; }
        public string ANH_NTH { get; set; }
    
        public virtual MANHTHUONGQUAN MANHTHUONGQUAN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TT_TRAOTANG> TT_TRAOTANG { get; set; }
    }
}
