//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NienLuanCoSo
{
    using System;
    using System.Collections.Generic;
    
    public partial class THANHVIEN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public THANHVIEN()
        {
            this.CHIENDICHes = new HashSet<CHIENDICH>();
            this.NOIHOTROes = new HashSet<NOIHOTRO>();
            this.TT_TRAOTANG = new HashSet<TT_TRAOTANG>();
        }
    
        public int MA_TV { get; set; }
        public string TEN_TV { get; set; }
        public string GIOITINH_TV { get; set; }
        public string DIACHI_TV { get; set; }
        public string SDT_TV { get; set; }
        public string EMAIL_TV { get; set; }
        public string MATKHAU_TV { get; set; }
        public Nullable<int> MA_CV { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHIENDICH> CHIENDICHes { get; set; }
        public virtual CHUCVU CHUCVU { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NOIHOTRO> NOIHOTROes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TT_TRAOTANG> TT_TRAOTANG { get; set; }
    }
}
