//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NienLuanCoSo
{
    using System;
    using System.Collections.Generic;
    
    public partial class TT_QUYENGOP_HIENVAT
    {
        public int MA_QGHV { get; set; }
        public int MA_HV { get; set; }
        public int MA_MTQ { get; set; }
        public Nullable<int> MA_CD { get; set; }
        public string GHICHU { get; set; }
        public Nullable<int> SOLUONG_QG { get; set; }
        public string TRANGTHAI_HV { get; set; }
        public Nullable<System.DateTime> Ngay_QG { get; set; }
    
        public virtual CHIENDICH CHIENDICH { get; set; }
        public virtual HIEN_VAT HIEN_VAT { get; set; }
        public virtual MANHTHUONGQUAN MANHTHUONGQUAN { get; set; }
    }
}
